### PR TITLE
Start TelegramLauncher with the command 'tdesk'

### PR DESCRIPTION
**Pull request by ghost**
`tdesk`, easy!

### CODE REVIEW

**Comment by peppelg** [comment]
allors

**Comment by peppelg** [comment]
ℹ️ sks me nn puo xk :ngarz: noi DOBBIAMO rifare telegramma lanciatore .

**Comment by TRIGGEREDNICK** [comment]
You can easily  accept this Pull Request.

**Comment by ghost** [comment]
Ok, I'll wait for your big update. ^^

**Comment by peppelg** [comment]
ma xk scrivete IN INGLESA

**Comment by peppelg** [comment]
QUESTA E ITALIANA ,CHAT

**Comment by ghost** [comment]
GitHub is an American project, and English is the international language.

**Pull request closed without merging**
